from Holamundo import saludo 
from Saludopers import saludopers
from Datospers import datospers
from Circulo import calcular_area_circulo
from Circulo import calcular_perimetro_circulo
from Segundosahoras import segundos_a_horas
from Multiplicar import tabla_multiplicar
from Basicas import operaciones_basicas
from Pesoyaltura import calcular_imc
from CelsiusaFarenheit import celsius_a_fahrenheit
from Promedio import calcular_promedio
